# Generated by Django 4.2.13 on 2024-07-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='creator',
            new_name='author',
        ),
    ]
