# Generated by Django 4.2.13 on 2024-07-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_thread_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.thread'),
            preserve_default=False,
        ),
    ]
